### ISSUE TITLE
Server Start code is going to run for every class that inherits from TestBase

### ISSUE THREAD

**Issue by PureWeen** [jfversluis/BasicAppiumSample#2]
![image](https://github.com/jfversluis/BasicAppiumSample/assets/5375137/1a080aeb-5c66-4f3e-bf10-aace91d5c33d)

If we want to keep the server start code as part of the sample we probably want it to check if the server is running and/or just start from a single place.

Not sure the best way to do this off hand with NUnit

I think in our tests we store it into a static variable

**Comment by sbanni** [comment]
[SetupFixture] that is defined outside of any namespace.

**Comment by jfversluis** [comment]
Yeah that was one thing I was going to investigate. I guess the OneTimeSetUp will be disregarded because each test will inherit from it and thus spin up multiple servers?

It probably won't hurt to put that in a completely separate class to be sure.

I know we talked about maybe not having the server spun up by the test itself at all, thoughts about that? 

@sbanni @PureWeen

**Comment by sbanni** [comment]
The problem with not having the test framework spin up the server is that either the test author needs to know and have in their tests which uri/port to connect to or the Appium Driver will end up starting the server when it gets created which will increase time to run tests depending on how they keep the driver/server around.

Because of this I am in favor of having the test framework spin up the server.

**Comment by jfversluis** [comment]
Finished sample is now available here: https://learn.microsoft.com/samples/dotnet/maui-samples/uitest-appium-nunit/
